theme: jekyll-theme-cayman
title: Udacity Google India Scholarship program
description: List of_config.yml
 projects created during Udacity Android Basics course
plugins:
  - jemoji
github:
is_project_page: true
